### ISSUE TITLE
Fix Responsiveness for Mobilegeddon

### ISSUE THREAD

**Issue by penguinho** [appium/appium.io#69]
Our mobile website looks really bad right now. We need to fix this for Mobilegeddon

**Comment by bootstraponline** [comment]
![mobile_friendly](https://cloud.githubusercontent.com/assets/1173057/7262625/2ab0ed38-e849-11e4-947b-92897433f210.png)
https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fappium.io%2F

I know slate isn't mobile friendly because we're using an old version. The main site seems fine according to the Google mobile friendly tool.

**Comment by penguinho** [comment]
![image](https://cloud.githubusercontent.com/assets/1672438/7269028/3fe6f62e-e8c7-11e4-88fc-e7eeadd52131.jpg)

**Comment by penguinho** [comment]
![image](https://cloud.githubusercontent.com/assets/1672438/7269043/62a0ae6c-e8c7-11e4-870c-091b068513db.jpg)

**Comment by bootstraponline** [comment]
Good catch. We should probably find a web dev to fix this properly.
